/* dark.js — after the light goes.
   ───────────────────────────────────────────────────────────────────
   You hit a jammed light switch with a hammer and made it worse. Now
   you are inside the thing, in the dark, and the only way out is to
   walk to the switch's guts and fit the part you found.

   Two objects in here: the grey DOOR (answers four times, then hands
   over the clicker) and the SWITCH (the exit — stand on it, press E).
   Neither is near the other, so the space has to be crossed twice.

   Decisions worth writing down:

   1. THE LIGHT IS STEPPED, NOT SMOOTH. A continuous radial falloff is
      the obvious way to do a torch and it looks wrong here — every
      other pixel on this site has a hard edge, so a soft vignette
      reads as a different program. Five discrete stops, visible rings.

   2. BOTH LANDMARKS GLOW FAINTLY FROM BEYOND THE TORCH, in different
      colours. Without that the space is a uniform black field and
      finding anything is a random walk, which is not exploration, it
      is waiting. Different hues so you can tell which is which from
      across the room.

   3. THE DEBRIS IS SEEDED, NOT RANDOM PER FRAME. You need landmarks
      to navigate by; scenery that reshuffles every frame is worse than
      no scenery, because it actively lies about where you are.

   4. THE WALK CYCLE ADVANCES ON DISTANCE, NOT ON TIME. Stepping every
      N milliseconds means the legs keep moving when you stop and slide
      when you change speed. Tying the frame to distance travelled
      makes the feet look like they are pushing the ground.          */

(function () {
  'use strict';

  var NEU = window.NEU = window.NEU || {};

  var wrap = document.getElementById('dk');
  var cv   = document.getElementById('dkCanvas');
  if (!wrap || !cv) { NEU.dark = { open: function () {}, close: function () {} }; return; }
  var ctx = cv.getContext ? cv.getContext('2d') : null;
  if (!ctx) { NEU.dark = { open: function () {}, close: function () {} }; return; }

  var W = 2600, H = 1800;
  var DOOR = { x: 2060, y: 1360, w: 74, h: 122 };
  var SWITCH = { x: 470, y: 1420, w: 66, h: 96 };   // far from the door on purpose
  var LIGHT = 132;

  var running = false, last = 0;
  var px = 420, py = 380, keys = {};
  var talks = 0, through = false, fixed = false;
  var msg = null, msgT = 0, found = false;
  var face = 'down', walked = 0, moving = false;
  var debris = [];

  /* ── the character ────────────────────────────────────────────────
     9x13 cells. 'h' hair, 's' skin, 'e' eye, 'c' coat, 'b' boot.
     Right is generated by mirroring left, so only three directions are
     authored by hand. */
  var PAL = { h: '#241d2e', s: '#E8DCC8', e: '#241d2e', c: '#6F5FA6', b: '#191426' };

  function mirror(rows) {
    return rows.map(function (r) { return r.split('').reverse().join(''); });
  }
  var BODY_DOWN = [
    '..hhhhh..',
    '.hhhhhhh.',
    '.hsssssh.',
    '.hsesesh.',
    '.hsssssh.',
    '..sssss..',
    '.ccccccc.',
    'scccccccs',
    '.ccccccc.',
    '..ccccc..'
  ];
  var BODY_UP = [
    '..hhhhh..',
    '.hhhhhhh.',
    '.hhhhhhh.',
    '.hhhhhhh.',
    '.hhhhhhh.',
    '..sssss..',
    '.ccccccc.',
    'scccccccs',
    '.ccccccc.',
    '..ccccc..'
  ];
  var BODY_LEFT = [
    '..hhhh...',
    '.hhhhhh..',
    '.hssssh..',
    '.essssh..',
    '.hssssh..',
    '..sssss..',
    '..ccccc..',
    '.sccccc..',
    '..ccccc..',
    '..cccc...'
  ];
  var LEGS = [
    ['..c...c..', '..b...b..', '..b...b..'],   // stand
    ['...c.c...', '...b.b...', '..b...b..'],   // step A
    ['..c...c..', '..bb.bb..', '..b...b..']    // step B
  ];
  var BODIES = { down: BODY_DOWN, up: BODY_UP, left: BODY_LEFT, right: mirror(BODY_LEFT) };

  function stamp(rows, cx, cy, s) {
    var h = rows.length, w = rows[0].length;
    var x0 = (cx - w * s / 2) | 0, y0 = (cy - h * s / 2) | 0;
    for (var r = 0; r < h; r++) for (var c = 0; c < w; c++) {
      var ch = rows[r][c];
      if (ch === '.' || !PAL[ch]) continue;
      ctx.fillStyle = PAL[ch];
      ctx.fillRect(x0 + c * s, y0 + r * s, s, s);
    }
  }

  function drawPlayer(sx, sy) {
    /* Frame from distance walked, not from the clock — see note 4. */
    var f = moving ? (1 + (((walked / 16) | 0) % 2)) : 0;
    var rows = BODIES[face].concat(LEGS[f]);
    stamp(rows, sx, sy, 2);
  }

  (function seedDebris() {
    var s = 20250815;
    function rnd() { s = (s * 1103515245 + 12345) & 0x7fffffff; return s / 0x7fffffff; }
    for (var i = 0; i < 90; i++) {
      debris.push({ x: rnd() * W, y: rnd() * H,
                    w: 12 + rnd() * 90, h: 8 + rnd() * 70,
                    c: rnd() < 0.25 ? '#191a24' : '#121219' });
    }
  })();

  var LINES = [
    'the door is warm. that is not how doors work.',
    'something behind it is counting. it is not counting up.',
    'it says you are early. it does not say what for.',
    'the handle turns now. it was always going to.'
  ];

  function say(s) { msg = s; msgT = performance.now(); }

  function layout() {
    var dpr = Math.min(devicePixelRatio || 1, 2);
    cv.width = (innerWidth * dpr) | 0; cv.height = (innerHeight * dpr) | 0;
    cv.style.width = innerWidth + 'px'; cv.style.height = innerHeight + 'px';
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.imageSmoothingEnabled = false;
  }
  addEventListener('resize', function () { if (running) layout(); });

  function near(o, r) {
    return Math.hypot(px - (o.x + o.w / 2), py - (o.y + o.h / 2)) < (r || 92);
  }
  /* Standing ON it, not just beside it — the ask was to walk on top. */
  function onSwitch() { return near(SWITCH, 54); }

  function interact() {
    if (onSwitch()) {
      if (fixed) { say('it works. you can go.'); return; }
      if (!(NEU.hasClicker && NEU.hasClicker())) {
        say('the switch, from the inside. the contact is snapped clean off.');
        return;
      }
      fixed = true;
      say('the clicker seats with a click. of course it does.');
      if (NEU.sfx && NEU.sfx.snap) NEU.sfx.snap();
      if (NEU.fitClicker) NEU.fitClicker();
      setTimeout(function () { close(); }, 1400);
      return;
    }

    if (!near(DOOR)) return;
    if (talks < LINES.length) {
      say(LINES[talks]); talks++;
      if (NEU.quest) NEU.quest.bump('answers', talks);
      if (NEU.sfx && NEU.sfx.locked) NEU.sfx.locked();
      return;
    }
    if (!through) {
      through = true;
      say('you step through. there is a small plastic thing on the floor.');
      if (NEU.sfx && NEU.sfx.snap) NEU.sfx.snap();
      if (NEU.quest) NEU.quest.mark('clicker');
      if (NEU.grantClicker) NEU.grantClicker();
      setTimeout(function () {
        say('"inter-conexion on-and-off wax free clicker". now find the switch.');
      }, 2600);
      return;
    }
    say('nothing else in here. the switch is your way out.');
  }

  function step(now) {
    if (!running) return;
    requestAnimationFrame(step);
    var dt = Math.min(0.033, (now - last) / 1000); last = now;

    var vx = (keys.right ? 1 : 0) - (keys.left ? 1 : 0);
    var vy = (keys.down ? 1 : 0) - (keys.up ? 1 : 0);
    if (vx && vy) { vx *= 0.7071; vy *= 0.7071; }
    moving = !!(vx || vy);

    /* Vertical wins ties so diagonal movement picks one sprite rather
       than flickering between two every frame. */
    if (vy < 0) face = 'up'; else if (vy > 0) face = 'down';
    else if (vx < 0) face = 'left'; else if (vx > 0) face = 'right';

    var dx = vx * 210 * dt, dy = vy * 210 * dt;
    px = Math.min(Math.max(px + dx, 20), W - 20);
    py = Math.min(Math.max(py + dy, 20), H - 20);
    walked += Math.hypot(dx, dy);

    if (!found && near(DOOR)) {
      found = true;
      if (NEU.quest) NEU.quest.mark('greydoor');
    }
    draw(now);
  }

  function glow(ox, oy, ow, oh, col, dist) {
    if (dist <= LIGHT * 0.6) return;
    ctx.globalAlpha = Math.max(0, (0.10 + 0.045 * Math.sin(performance.now() / 420)) *
                                  Math.min(1, 900 / dist));
    ctx.fillStyle = col;
    ctx.fillRect(ox - 8, oy - 8, ow + 16, oh + 16);
    ctx.globalAlpha = 1;
  }

  function draw(now) {
    var w = innerWidth, h = innerHeight;
    var camX = px - w / 2, camY = py - h / 2;

    ctx.fillStyle = '#050507';
    ctx.fillRect(0, 0, w, h);

    for (var i = 0; i < debris.length; i++) {
      var d = debris[i];
      ctx.fillStyle = d.c;
      ctx.fillRect((d.x - camX) | 0, (d.y - camY) | 0, d.w | 0, d.h | 0);
    }

    /* the grey door */
    var dx = (DOOR.x - camX) | 0, dy = (DOOR.y - camY) | 0;
    ctx.fillStyle = through ? '#3b3b48' : '#2a2a34';
    ctx.fillRect(dx, dy, DOOR.w, DOOR.h);
    ctx.fillStyle = '#4a4a5a';
    ctx.fillRect(dx, dy, DOOR.w, 4); ctx.fillRect(dx, dy, 4, DOOR.h);
    ctx.fillRect(dx + DOOR.w - 4, dy, 4, DOOR.h);
    ctx.fillStyle = '#8A8598';
    ctx.fillRect(dx + DOOR.w - 20, dy + ((DOOR.h / 2) | 0), 8, 8);
    if (talks >= LINES.length) {
      ctx.fillStyle = '#B892FF';
      ctx.fillRect(dx + 6, dy + 6, DOOR.w - 12, DOOR.h - 10);
    }

    /* the switch, from the inside */
    var kx = (SWITCH.x - camX) | 0, ky = (SWITCH.y - camY) | 0;
    ctx.fillStyle = '#1b1b24'; ctx.fillRect(kx, ky, SWITCH.w, SWITCH.h);
    ctx.fillStyle = fixed ? '#C9A227' : '#4a4a5a';
    ctx.fillRect(kx, ky, SWITCH.w, 4); ctx.fillRect(kx, ky + SWITCH.h - 4, SWITCH.w, 4);
    ctx.fillRect(kx, ky, 4, SWITCH.h); ctx.fillRect(kx + SWITCH.w - 4, ky, 4, SWITCH.h);
    /* the snapped contact: a lever hanging at a broken angle until fixed */
    ctx.fillStyle = fixed ? '#B892FF' : '#8C2F4A';
    if (fixed) ctx.fillRect(kx + 22, ky + 20, 22, 52);
    else { ctx.fillRect(kx + 22, ky + 20, 22, 22); ctx.fillRect(kx + 34, ky + 48, 10, 10); }

    drawPlayer((px - camX) | 0, (py - camY) | 0);

    /* the dark, punched through in five hard steps */
    var g = ctx.createRadialGradient(w / 2, h / 2, 0, w / 2, h / 2, LIGHT);
    g.addColorStop(0.00, 'rgba(0,0,0,1)');
    g.addColorStop(0.45, 'rgba(0,0,0,1)');
    g.addColorStop(0.46, 'rgba(0,0,0,0.72)');
    g.addColorStop(0.70, 'rgba(0,0,0,0.72)');
    g.addColorStop(0.71, 'rgba(0,0,0,0.34)');
    g.addColorStop(1.00, 'rgba(0,0,0,0)');
    ctx.globalCompositeOperation = 'destination-in';
    ctx.fillStyle = g; ctx.fillRect(0, 0, w, h);
    ctx.globalCompositeOperation = 'source-over';

    /* Landmarks glow in different hues so you can tell them apart from
       across a black room: violet is the door, amber is the way out. */
    glow(dx, dy, DOOR.w, DOOR.h, '#B892FF',
         Math.hypot(px - (DOOR.x + DOOR.w / 2), py - (DOOR.y + DOOR.h / 2)));
    glow(kx, ky, SWITCH.w, SWITCH.h, '#C9A227',
         Math.hypot(px - (SWITCH.x + SWITCH.w / 2), py - (SWITCH.y + SWITCH.h / 2)));

    if (near(DOOR) || onSwitch()) {
      ctx.fillStyle = '#EDE7DE';
      ctx.font = '16px "Determination Mono","Pixelify Sans",monospace';
      ctx.textAlign = 'center';
      ctx.fillText('press E', w / 2, h / 2 - 46);
      ctx.textAlign = 'left';
    }

    if (msg && now - msgT < 6000) {
      var bw = Math.min(680, w - 48), bx = ((w - bw) / 2) | 0, by = h - 132;
      ctx.fillStyle = '#000'; ctx.fillRect(bx, by, bw, 84);
      ctx.fillStyle = '#EDE7DE';
      ctx.fillRect(bx, by, bw, 3); ctx.fillRect(bx, by + 81, bw, 3);
      ctx.fillRect(bx, by, 3, 84); ctx.fillRect(bx + bw - 3, by, 3, 84);
      ctx.font = '16px "Determination Mono","Pixelify Sans",monospace';
      ctx.textBaseline = 'top';
      ctx.fillText(msg, bx + 20, by + 30);
    }
  }

  function name(e) {
    var k = e.key;
    if (k === 'ArrowLeft'  || k === 'a' || k === 'A') return 'left';
    if (k === 'ArrowRight' || k === 'd' || k === 'D') return 'right';
    if (k === 'ArrowUp'    || k === 'w' || k === 'W') return 'up';
    if (k === 'ArrowDown'  || k === 's' || k === 'S') return 'down';
    return null;
  }
  addEventListener('keydown', function (e) {
    if (wrap.hidden) return;
    if (e.key === 'Escape') { close(); return; }
    if (e.key === 'e' || e.key === 'E' || e.key === ' ') { e.preventDefault(); interact(); return; }
    var n = name(e); if (n) { keys[n] = true; e.preventDefault(); }
  });
  addEventListener('keyup', function (e) {
    if (wrap.hidden) return;
    var n = name(e); if (n) keys[n] = false;
  });

  function open() {
    wrap.hidden = false;
    document.body.classList.add('is-playing');
    layout();
    keys = {}; moving = false; running = true; last = performance.now();
    if (NEU.quest) { NEU.quest.mark('smash'); NEU.quest.lock(true); }
    requestAnimationFrame(step);
  }
  function close() {
    running = false;
    wrap.hidden = true;
    document.body.classList.remove('is-playing');
    if (NEU.quest) NEU.quest.lock(false);
  }

  var q = document.getElementById('dkQuit');
  if (q) q.addEventListener('click', close);

  NEU.dark = {
    open: open, close: close,
    /* dev: the door is a deliberate long walk, which is right once and
       wrong the fortieth time. */
    warp:   function () { px = DOOR.x - 46;   py = DOOR.y + DOOR.h / 2; },
    warpSw: function () { px = SWITCH.x + 30; py = SWITCH.y + SWITCH.h / 2; },
    interact: interact,
    get running() { return running; },
    get talks() { return talks; },
    get through() { return through; },
    get fixed() { return fixed; }
  };
})();
