/* engine.js — rooms, as data.
   ───────────────────────────────────────────────────────────────────
   Act IV is ~35 rooms. The existing scenes each hand-code their own
   movement, their own collision and their own interaction, which was
   right for three of them and is how a codebase dies at thirty-five:
   thirty-five slightly different collision bugs, none of them the same
   shape twice.

   So: one implementation, and rooms become DATA.

   The five decisions this file rests on:

   1. TILES ARE A STRING, one character per cell. A room is about a
      kilobyte of text you can read and edit in place. Binary or JSON
      arrays would be smaller and completely unreadable, and the thing
      that actually costs time here is authoring, not bytes.

   2. TILESETS HAVE A PALETTE FALLBACK. A tileset can point at an
      atlas image OR at a table of flat colours. That means every room
      is playable and testable the moment its layout exists, before
      any art for it does — no phase is ever blocked waiting on a
      sprite sheet.

   3. COLLISION IS SWEPT, ALWAYS. The player moves fast enough to
      cross a 16px tile in a frame at 60fps and much further on a
      120Hz display. Point-testing the destination tunnels through
      walls; the same bug already cost this project a round when the
      thrown key passed through the cube door. Movement is resolved
      axis-by-axis against the tiles the whole segment crosses.

   4. THE WALK CYCLE ADVANCES ON DISTANCE, NOT TIME. Lifted verbatim
      out of dark.js, which is where it was proven. Time-driven legs
      keep walking when you stop and slide when you change speed.

   5. THE CAMERA HAS A DEAD ZONE AND CLAMPS TO THE ROOM. Without a
      dead zone the whole world jitters under a player who is nudging
      one pixel at a time; without clamping you see past the edge of
      the map, which instantly reads as broken.

   Everything renders with integer fillRect / drawImage at DPR with
   smoothing off — same rules as the rest of the site.               */

(function () {
  'use strict';

  var NEU = window.NEU = window.NEU || {};

  var wrap = document.getElementById('eng');
  var cv   = document.getElementById('engCanvas');
  if (!wrap || !cv) { NEU.engine = { enter: function () {}, leave: function () {} }; return; }
  var ctx = cv.getContext ? cv.getContext('2d') : null;
  if (!ctx) { NEU.engine = { enter: function () {}, leave: function () {} }; return; }

  var reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;

  var TILE = 16;              // world units per cell
  var SCALE = 3;              // drawn at 3x — 48px cells, readable, pixel-exact
  var SPEED = 96;             // world units/sec
  var PLAYER_W = 10, PLAYER_H = 8;   // the FEET box. smaller than the sprite.
  var REACH = 22;

  /* ── state ────────────────────────────────────────────────────── */
  var rooms = {}, tilesets = {};
  var room = null, running = false, last = 0;
  var px = 0, py = 0, keys = {}, face = 'down', walked = 0, moving = false;
  var camX = 0, camY = 0;
  var fade = 0, fadeDir = 0, fadeThen = null;
  var busy = false;                    // a cutscene owns input
  var ents = [];                       // live copy of room.entities
  var images = {};

  /* ── the character ────────────────────────────────────────────────
     Same 9x13 cells as dark.js. Right is generated by mirroring left,
     so only three directions are drawn by hand. */
  var PAL = { h: '#241d2e', s: '#E8DCC8', e: '#241d2e', c: '#6F5FA6', b: '#191426' };
  function mirror(rows) {
    return rows.map(function (r) { return r.split('').reverse().join(''); });
  }
  var BODY_DOWN = ['..hhhhh..','.hhhhhhh.','.hsssssh.','.hsesesh.','.hsssssh.',
                   '..sssss..','.ccccccc.','scccccccs','.ccccccc.','..ccccc..'];
  var BODY_UP   = ['..hhhhh..','.hhhhhhh.','.hhhhhhh.','.hhhhhhh.','.hhhhhhh.',
                   '..sssss..','.ccccccc.','scccccccs','.ccccccc.','..ccccc..'];
  var BODY_LEFT = ['..hhhh...','.hhhhhh..','.hssssh..','.essssh..','.hssssh..',
                   '..sssss..','..ccccc..','.sccccc..','..ccccc..','..cccc...'];
  var LEGS = [['..c...c..','..b...b..','..b...b..'],
              ['...c.c...','...b.b...','..b...b..'],
              ['..c...c..','..bb.bb..','..b...b..']];
  var BODIES = { down: BODY_DOWN, up: BODY_UP, left: BODY_LEFT, right: mirror(BODY_LEFT) };

  function stamp(rows, cx, cy, s) {
    var h = rows.length, w = rows[0].length;
    var x0 = (cx - w * s / 2) | 0, y0 = (cy - h * s) | 0;   // anchored at the feet
    for (var r = 0; r < h; r++) for (var c = 0; c < w; c++) {
      var ch = rows[r][c];
      if (ch === '.' || !PAL[ch]) continue;
      ctx.fillStyle = PAL[ch];
      ctx.fillRect(x0 + c * s, y0 + r * s, s, s);
    }
  }

  /* ── prop sprites ─────────────────────────────────────────────────
     Same ASCII-rows-plus-a-palette form the player is drawn in, because
     that is this project's pixel-art primitive and a second one would be
     a second thing to keep on the grid. Drawn at SCALE, the size a tile
     pixel is, so props sit on the same grid as the world they stand in.

     These two are here rather than in a PNG because there is no art in
     the repo for either: the altar and the save point were falling
     through drawEnt to the generic 18x18 square, so the stone bowl the
     room describes at length ("a stone bowl on a stone plinth… a ring of
     ash in it") was a lilac rectangle. Colours are the castle ramp's
     own, plus the save star in the brazier's warm pair. */
  var PROP = {
    /* The bowl has to be LIGHTER than the plinth it stands on. The
       plinth tile is #6A5C74 and the first draft used the castle's dark
       stone, so the altar read as a hole punched in its own plinth —
       the exact failure the 'A' tile was added to fix in the first
       place (see the comment on the castle tileset). */
    altar: { pal: { k: '#2A2238', s: '#8A8598', l: '#C4B8CC', a: '#4A4560' },
             rows: ['...kkkkk...',
                    '..klllllk..',
                    '..klaaalk..',
                    '..kklllkk..',
                    '...kkkkk...',
                    '....sss....',
                    '....sss....',
                    '...sssss...',
                    '..kssssskk.',
                    '..kkkkkkkk.'] },
    save:  { pal: { y: '#E4C46A', w: '#FFF2C4', k: '#8F7016' },
             rows: ['....k....',
                    '....y....',
                    '...kyk...',
                    '.kkyywkk.',
                    'kyywwwyyk',
                    '.kkyywkk.',
                    '...kyk...',
                    '....y....',
                    '....k....'] }
  };

  function stampPal(rows, pal, cx, cy, s) {
    var h = rows.length, w = rows[0].length;
    var x0 = (cx - w * s / 2) | 0, y0 = (cy - h * s) | 0;
    for (var r = 0; r < h; r++) for (var c = 0; c < w; c++) {
      var ch = rows[r][c];
      if (ch === '.' || !pal[ch]) continue;
      ctx.fillStyle = pal[ch];
      ctx.fillRect(x0 + c * s, y0 + r * s, s, s);
    }
  }

  function drawPlayer(targetCtx, sx, sy, fce, wlk, mov, anchorFeet, sc) {
    var c = targetCtx || ctx;
    var s = sc || 2;
    var f = mov ? (1 + (((wlk / (anchorFeet ? 10 : 16)) | 0) % 2)) : 0;
    var rows = BODIES[fce || 'down'].concat(LEGS[f]);
    var h = rows.length, w = rows[0].length;
    var x0 = (sx - w * s / 2) | 0;
    var y0 = anchorFeet ? ((sy - h * s) | 0) : ((sy - h * s / 2) | 0);
    for (var r = 0; r < h; r++) for (var cl = 0; cl < w; cl++) {
      var ch = rows[r][cl];
      if (ch === '.' || !PAL[ch]) continue;
      c.fillStyle = PAL[ch];
      c.fillRect(x0 + cl * s, y0 + r * s, s, s);
    }
  }

  /* ── tilesets ─────────────────────────────────────────────────── */
  function tileset(name, def) {
    /* def = { solid:'#XT', colours:{ '#':'#1a1a24', '.':'#0d0d12' },
               src:'img/...png', rects:{ '#':[0,0], '.':[16,0] } }     */
    tilesets[name] = def;
    if (def.src) img(def.src);
    return def;
  }

  function img(src) {
    if (images[src]) return images[src];
    var i = new Image();
    i.onerror = function () { i.__failed = true; };
    i.src = src;
    images[src] = i;
    return i;
  }

  /* ── rooms ────────────────────────────────────────────────────── */
  function register(id, def) {
    def.id = id;
    def.grid = def.tiles.split('\n').filter(function (r) { return r.length; });
    def.h = def.grid.length;
    def.w = def.grid.reduce(function (m, r) { return Math.max(m, r.length); }, 0);
    rooms[id] = def;
    return def;
  }

  function at(cx, cy) {
    if (!room) return '#';
    if (cx < 0 || cy < 0 || cy >= room.h) return '#';
    var r = room.grid[cy];
    if (cx >= r.length) return '#';
    return r[cx];
  }

  function solidAt(cx, cy) {
    var ts = tilesets[room.tileset];
    var ch = at(cx, cy);
    return !ts || ts.solid.indexOf(ch) >= 0;
  }

  /* Box-vs-tiles. Tests every cell the box overlaps rather than its
     corners — a box wider than a tile can straddle a wall with all
     four corners in open space. */
  function blocked(x, y) {
    var x0 = Math.floor((x - PLAYER_W / 2) / TILE);
    var x1 = Math.floor((x + PLAYER_W / 2 - 0.01) / TILE);
    var y0 = Math.floor((y - PLAYER_H) / TILE);
    var y1 = Math.floor((y - 0.01) / TILE);
    for (var cy = y0; cy <= y1; cy++)
      for (var cx = x0; cx <= x1; cx++) {
        if (solidAt(cx, cy)) return true;
        if (entSolid(cx, cy)) return true;
      }
    return false;
  }

  /* Entities can occupy the grid too — a push block is not a tile,
     because tiles are immutable strings and a block that moves has to
     be a thing with a position. */
  function entSolid(cx, cy) {
    for (var i = 0; i < ents.length; i++) {
      var e = ents[i];
      if (e.dead || !e.solid) continue;
      if (e.x === cx && e.y === cy) return true;
    }
    return false;
  }

  function entHere(cx, cy, kind) {
    for (var i = 0; i < ents.length; i++) {
      var e = ents[i];
      if (e.dead) continue;
      if (e.x === cx && e.y === cy && (!kind || e.t === kind)) return e;
    }
    return null;
  }

  var lastReset = 0;
  var slideD = 0;   /* direction of an active ice slide; 0 = not sliding */
  var slideDead = false;  /* the direction a slide just died in — a held key must not re-commit */

  /* ── push blocks ────────────────────────────────────────────────
     Walk into one and it moves a whole cell in the direction you are
     facing, if the cell beyond is clear. Grid-snapped rather than
     free — a block that slides continuously can end up straddling two
     cells, and then "is it on the plate" has no honest answer.

     There is no undo. Instead, an unsolvable arrangement resets the
     WHOLE room (`resetPuzzle`), which is Deltarune's answer and the
     right one: undo makes you think about the interface, a reset makes
     you think about the puzzle. */
  var DIRV = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] };

  function tryPush() {
    var d = DIRV[face];
    if (!d) return false;
    /* the cell directly in front of the player's feet */
    var cx = Math.floor(px / TILE) + d[0];
    var cy = Math.floor((py - 1) / TILE) + d[1];
    var b = entHere(cx, cy, 'block');
    if (!b || !b.push) return false;
    var tx = cx + d[0], ty = cy + d[1];
    if (solidAt(tx, ty) || entSolid(tx, ty)) return false;
    b.x = tx; b.y = ty;
    if (NEU.juice) NEU.juice.hit('tick');
    /* Ice. The block keeps going until something stops it, which is
       what turns "push a block" into "aim a block". Bounded by the
       room size so a malformed map cannot spin forever. */
    var guard = 0;
    while (at(b.x, b.y) === 'i' && guard++ < 64) {
      var nx = b.x + d[0], ny = b.y + d[1];
      if (solidAt(nx, ny) || entSolid(nx, ny)) break;
      b.x = nx; b.y = ny;
    }
    if (NEU.sfx && NEU.sfx.snap) NEU.sfx.snap();
    checkPuzzle();
    return true;
  }

  /* A slide dies on the last ice cell. If that cell holds a slideOnly
     plate, the plate locks — arming by landing, never by walking up
     to it, which is what keeps the ice route honest. */
  function stopSlide() {
    var ci = Math.floor(px / TILE), cj = Math.floor((py - 1) / TILE);
    var pl = entHere(ci, cj, 'plate');
    if (pl && pl.slideOnly && !pl.armed) {
      pl.armed = true;
      if (NEU.sfx && NEU.sfx.snap) NEU.sfx.snap();
      if (NEU.juice) NEU.juice.hit('small');
    }
    slideD = 0;
    slideDead = true;
    checkPuzzle();
  }

  /* A room is solved when every plate has a block on it. Rooms can
     override with their own `solved(ctx)` for the ones that are not
     about blocks. */
  function checkPuzzle() {
    if (!room || room.__solved) return;
    var done;
    if (typeof room.solved === 'function') done = room.solved(API);
    else {
      var plates = ents.filter(function (e) { return e.t === 'plate' && !e.dead; });
      done = plates.length > 0 && plates.every(function (p) {
        var b = entHere(p.x, p.y, 'block');
        return !!b;
      });
    }
    if (!done) return;
    room.__solved = true;
    if (NEU.sfx && NEU.sfx.tick) NEU.sfx.tick();
    /* Solving a room is a LARGE moment. It is the only reward the
       puzzle gives and it should feel like one. */
    if (NEU.juice) NEU.juice.hit('large', { colour: '#7BE38A' });
    if (room.onSolved) room.onSolved(API);
  }

  function resetPuzzle() {
    if (!room) return;
    /* R-spam is the cheese: brute-forcing a puzzle by resetting every
       second is not solving it. The room needs a moment to settle, and
       it says so instead of silently ignoring the press. */
    if (performance.now() - lastReset < 4000) {
      say(['the room is still settling. give it a moment.'], 'narr');
      return;
    }
    lastReset = performance.now();
    room.__solved = false;
    slideD = 0;
    slideDead = false;
    ents = spawnEnts(room);
    /* Rooms keep their own working state (a light sequence, a carried
       torch, a mirror that was turned) in closures that re-spawning
       entities cannot reach — give them a hook so a reset is honest. */
    if (room.onReset) room.onReset();
    say(['the room resets itself. it has done this before.'], 'narr');
  }

  /* Swept along one axis: step in whole sub-steps no larger than half
     a tile, stopping at the last legal position. This is what stops
     fast movement tunnelling, and it degrades gracefully on a slow
     frame instead of teleporting through a wall. */
  function sweep(x, y, dx, dy) {
    var dist = Math.hypot(dx, dy);
    if (!dist) return { x: x, y: y };
    var steps = Math.max(1, Math.ceil(dist / (TILE / 2)));
    var sx = dx / steps, sy = dy / steps;
    for (var i = 0; i < steps; i++) {
      if (!blocked(x + sx, y)) x += sx;
      if (!blocked(x, y + sy)) y += sy;
    }
    return { x: x, y: y };
  }

  /* ── entities ─────────────────────────────────────────────────── */
  function entAt(e) { return { x: (e.x + 0.5) * TILE, y: (e.y + 1) * TILE }; }

  /* What `fire` can actually DO something with — the list below is
     exactly the set of branches fire() has.

     This exists because the E handler was `if (nearest()) fire(it); else
     tryPush()`, and `nearest` returned whatever entity was closest
     including blocks and plates. fire() has no branch for either, so it
     returned in silence and tryPush() was never reached: standing
     correctly against a block with open floor beyond it and pressing e
     did nothing, in every room, for every block. Every block puzzle in
     the game was unsolvable no matter how the room was laid out. */
  function interactive(e) {
    return typeof e.run === 'function' ||
           e.t === 'exit' || e.t === 'pickup' || e.t === 'save' ||
           e.t === 'npc'  || e.t === 'altar' || e.t === 'sign';
  }

  /* A pushable block is worth an `e` prompt even though pressing e goes
     through tryPush rather than fire. A plate is not: it is floor paint
     and there has never been anything to press. */
  function promptable(e) { return interactive(e) || (e.t === 'block' && e.push); }

  function nearest(want) {
    var best = null, bd = REACH;
    for (var i = 0; i < ents.length; i++) {
      var e = ents[i];
      if (e.dead || e.t === 'trigger') continue;
      if (want && !want(e)) continue;
      var p = entAt(e);
      var d = Math.hypot(p.x - px, p.y - (py - PLAYER_H / 2));
      if (d < bd) { bd = d; best = e; }
    }
    return best;
  }

  /* ── interaction state ──────────────────────────────────────────────
   Track last interacted entity to prevent dialog reset on rapid E presses. */
  var lastInteractedEntity = null, lastInteractedTime = 0;
  const INTERACT_COOLDOWN = 500; // ms

  function fire(e) {
    if (!e) return;
    var now = Date.now();
    /* Prevent dialog reset on repeated E press on same entity */
    if (e === lastInteractedEntity && now - lastInteractedTime < INTERACT_COOLDOWN) {
      return;
    }
    lastInteractedEntity = e;
    lastInteractedTime = now;
    if (e.t === 'exit') {
      /* A locked door says what it is waiting for. "Nothing happens"
         is the least useful sentence a game can produce. */
      if (e.locked && !(NEU.save && NEU.save.flagged(e.locked))) {
        say(e.lines || ['it will not move yet.'], 'narr');
        if (NEU.sfx && NEU.sfx.locked) NEU.sfx.locked();
        return;
      }
      go(e.to, e.spawn); return;
    }
    if (e.t === 'pickup') {
      if (e.dead) return;
      e.dead = true;
      NEU.save && NEU.save.give(e.item);
      say(e.lines || ['you take it.'], e.who || 'narr');
      NEU.sfx && NEU.sfx.snap && NEU.sfx.snap();
      /* SMALL. A pickup must register without competing with a boss
         death — the tier table is what keeps that honest. */
      if (NEU.juice) {
        var pp = entAt(e);
        NEU.juice.hit('small');
        NEU.juice.burst((pp.x - camX) * SCALE, (pp.y - camY) * SCALE, 10, '#B892FF');
      }
      return;
    }
    if (e.t === 'save') {
      NEU.save && NEU.save.capture();
      NEU.save && NEU.save.flush();
      say(['saved.'], 'narr');
      NEU.sfx && NEU.sfx.tick && NEU.sfx.tick();
      return;
    }
    if (e.t === 'sign') {
      /* A hint the player asked for by walking up to it. Signs are
         read, never consumed, and they always answer in narration. */
      say(e.lines || ['a wooden sign. nothing else.'], 'narr');
      NEU.sfx && NEU.sfx.tick && NEU.sfx.tick();
      return;
    }
    if (e.t === 'npc') {
      /* A run hook wins over lines. Entities that are only a hook —
         the mushrooms, the witch, the merchant — answer differently
         depending on the state of the world, and a fixed `lines`
         array cannot do that. */
      if (typeof e.run === 'function') { e.run(API); return; }
      /* E while a talk is showing is a no-op. Restarting a dialogue
         mid-line read as the box resetting under your thumb. */
      if (NEU.tboxOpen && NEU.tboxOpen()) return;
      var dk = 'd:' + room.id + ':' + e.x + ',' + e.y;
      var at = NEU.save ? (NEU.save.flag(dk) || 0) : 0;
      var base = e.lines || ['...'];
      var total = base.length;
      var who = e.who || 'narr';
      /* Picked up where they left off: resume from the line they were
         at, capped with a closing beat. Finished talks replay whole. */
      var lines = (at > 0 && at < total)
        ? base.slice(at).concat(e.close || ['...'])
        : base;
      say(lines, who);
      if (NEU.talkWatch) {
        var seen = at;
        NEU.talkWatch(function (i) {
          if (i < 0) {
            NEU.talkUnwatch();
            if (NEU.save) NEU.save.flag(dk, seen >= total ? 0 : seen);
            return;
          }
          seen = at + i;
        });
      }
      return;
    }
    if (e.t === 'altar') {
      if (!NEU.save || !NEU.save.has(e.needs)) {
        say(e.empty || ['it wants something you do not have.'], 'narr');
        return;
      }
      NEU.save.take(e.needs);
      flag(e.gives, 1);
      say(e.lines || ['it takes it.'], 'narr');
      return;
    }
    if (typeof e.run === 'function') e.run(API);
  }

  function checkTriggers() {
    for (var i = 0; i < ents.length; i++) {
      var e = ents[i];
      if (e.t !== 'trigger' || e.dead) continue;
      var x0 = e.x * TILE, y0 = e.y * TILE;
      var x1 = x0 + (e.w || 1) * TILE, y1 = y0 + (e.h || 1) * TILE;
      if (px >= x0 && px <= x1 && py >= y0 && py <= y1) {
        if (e.once) e.dead = true;
        if (typeof e.run === 'function') e.run(API);
      }
    }
  }

  /* ── transitions ──────────────────────────────────────────────── */
  function go(id, spawn) {
    if (!rooms[id]) { say(['there is nothing through there. yet.'], 'narr'); return; }
    if (fadeDir) return;                    // already moving
    busy = true;
    fadeDir = 1;
    fadeThen = function () {
      land(id, spawn);
      fadeDir = -1;
      fadeThen = function () { busy = false; };
    };
    if (reduced) { fade = 1; }              // no crossfade, just the cut
  }

  function spawnEnts(r) {
    return (r.entities || []).map(function (e) {
      var c = {}; for (var k in e) c[k] = e[k];
      /* Pickups already taken and one-shot triggers already fired stay
         gone across a reload — otherwise the save file quietly hands
         out infinite copies of every item. */
      if (c.t === 'pickup' && NEU.save && NEU.save.has(c.item)) c.dead = true;
      if (c.once && NEU.save && NEU.save.flagged('t:' + r.id + ':' + c.x + ',' + c.y)) c.dead = true;
      return c;
    });
  }

  /* Only reached by a room that declares no spawns at all: the first cell
     you could actually stand in, in reading order. */
  function firstOpenCell() {
    for (var y = 0; y < room.h; y++)
      for (var x = 0; x < room.w; x++)
        if (!solidAt(x, y)) return { x: x, y: y };
    return { x: 2, y: 2 };
  }

  function land(id, spawn) {
    if (room && room.onExit) room.onExit(API);
    room = rooms[id];
    /* A solved puzzle stays solved across a revisit, but the blocks go
       back to their starting cells — otherwise re-entering a solved
       room shows an arrangement that no longer means anything. */
    room.__solved = NEU.save ? NEU.save.flagged('solved:' + id) : false;
    ents = spawnEnts(room);
    var s = (room.spawns && room.spawns[spawn]) || (room.spawns && room.spawns.default);
    if (!s) {
      /* An exit naming a spawn the target room does not declare used to
         fall through to a hard-coded {x:2,y:2}. That cell is inside a
         wall in four of the rooms shipped here and the wrong end of the
         room in the rest, so a single typo in an exit became a silent
         soft-lock that no spawn check could see — d3_square was exactly
         this. Prefer any spawn the room really declares, then go looking
         for floor, and say so out loud: a missing spawn is a bug in the
         room and it should not be able to pass for level design. */
      var names = room.spawns ? Object.keys(room.spawns) : [];
      s = names.length ? room.spawns[names[0]] : firstOpenCell();
      if (window.console && console.warn)
        console.warn('[neu] room "' + id + '" has no spawn "' + spawn +
                     '" — landing at ' + s.x + ',' + s.y);
    }
    px = (s.x + 0.5) * TILE; py = (s.y + 1) * TILE;
    walked = 0; face = s.face || 'down';
    room.__spawn = spawn;
    camSnap();
    /* A room change must not carry the old room's dialogue. The talk
       box is global; without this, walking through a door while a line
       is typing leaves that text on screen for good — the new room's
       onEnter only replaces it if the room actually has lines to say. */
    if (NEU.talk && NEU.talk.close) NEU.talk.close();
    if (room.onEnter) room.onEnter(API);
    if (NEU.save) NEU.save.capture();
  }

  /* ── camera ───────────────────────────────────────────────────── */
  function view() {
    return { w: innerWidth / SCALE, h: innerHeight / SCALE };
  }
  function camClamp() {
    var v = view();
    var maxX = Math.max(0, room.w * TILE - v.w), maxY = Math.max(0, room.h * TILE - v.h);
    camX = Math.min(Math.max(camX, 0), maxX);
    camY = Math.min(Math.max(camY, 0), maxY);
    if (room.w * TILE < v.w) camX = (room.w * TILE - v.w) / 2;
    if (room.h * TILE < v.h) camY = (room.h * TILE - v.h) / 2;
  }
  function camSnap() {
    var v = view();
    camX = px - v.w / 2; camY = py - v.h / 2;
    camClamp();
  }
  function camFollow() {
    /* Dead zone: the camera only moves once the player leaves the
       middle third. Without it, one-pixel nudges shake the world. */
    var v = view();
    var dzx = v.w * 0.16, dzy = v.h * 0.16;
    var cx = camX + v.w / 2, cy = camY + v.h / 2;
    if (px - cx >  dzx) camX += (px - cx) - dzx;
    if (px - cx < -dzx) camX += (px - cx) + dzx;
    if (py - cy >  dzy) camY += (py - cy) - dzy;
    if (py - cy < -dzy) camY += (py - cy) + dzy;
    camClamp();
  }

  /* ── loop ─────────────────────────────────────────────────────── */
  function layout() {
    var dpr = Math.min(devicePixelRatio || 1, 2);
    cv.width = (innerWidth * dpr) | 0; cv.height = (innerHeight * dpr) | 0;
    cv.style.width = innerWidth + 'px'; cv.style.height = innerHeight + 'px';
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.imageSmoothingEnabled = false;
    if (room) camClamp();
  }
  addEventListener('resize', function () { if (running) layout(); });

  function step(now) {
    if (!running) return;
    requestAnimationFrame(step);
    var dt = Math.min(0.033, (now - last) / 1000); last = now;

    if (fadeDir) {
      fade += fadeDir * dt / 0.22;
      if (fade >= 1 && fadeDir > 0) { fade = 1; fadeDir = 0; var f = fadeThen; fadeThen = null; f && f(); }
      else if (fade <= 0 && fadeDir < 0) { fade = 0; fadeDir = 0; var g = fadeThen; fadeThen = null; g && g(); }
    }

    if (room && !busy) {
      var vx = (keys.right ? 1 : 0) - (keys.left ? 1 : 0);
      var vy = (keys.down ? 1 : 0) - (keys.up ? 1 : 0);
      moving = !!(vx || vy);
      if (vx && vy) { vx *= 0.7071; vy *= 0.7071; }
      /* A fresh press is a fresh commitment; the key that killed a
         slide must not immediately re-commit to the same line, or
         walking off the end of the ice would stutter frame by frame. */
      if (!vx && !vy) slideDead = false;
      if (moving && !slideD) {
        face = Math.abs(vx) > Math.abs(vy) ? (vx > 0 ? 'right' : 'left')
                                           : (vy > 0 ? 'down' : 'up');
        var before = px, bY = py;
        var p = sweep(px, py, vx * SPEED * dt, vy * SPEED * dt);
        px = p.x; py = p.y;
        walked += Math.hypot(px - before, py - bY);
        /* Ice catches you: the moment your feet are on it, you are
           committed to that line of travel. No turning, no stopping —
           that is the whole puzzle. */
        var eci = Math.floor(px / TILE), ecj = Math.floor((py - 1) / TILE);
        if (at(eci, ecj) === 'i' && !slideDead) slideD = face;
        checkTriggers();
        /* A room's solved() can become true on a WALK, not just on a
           push — b5 needs you standing on one plate while the block
           holds the other, and the walk onto the plate is the final
           move. Check every moving frame; __solved makes it a no-op
           once the room is done. */
        checkPuzzle();
      } else if (slideD) {
        /* Sliding: input does nothing until the ice runs out. */
        face = slideD;
        var d = DIRV[slideD];
        var ci = Math.floor(px / TILE), cj = Math.floor((py - 1) / TILE);
        var ni = ci + d[0], nj = cj + d[1];
        /* Predict before moving: the slide dies when the cell ahead is
           not ice, so the stop lands exactly ON the last ice cell —
           checking after the move would overshoot by a frame and miss
           the plate that sits there. */
        if (at(ci, cj) !== 'i' || at(ni, nj) !== 'i') {
          stopSlide();
          checkTriggers();
          checkPuzzle();
        } else {
          var bp = px, bq = py;
          var sp2 = sweep(px, py, d[0] * SPEED * dt, d[1] * SPEED * dt);
          px = sp2.x; py = sp2.y;
          walked += Math.hypot(px - bp, py - bq);
          checkTriggers();
          checkPuzzle();
        }
      }
      camFollow();
    }
    draw(now);
  }

  function draw(now) {
    var w = innerWidth, h = innerHeight;
    ctx.fillStyle = '#08080B'; ctx.fillRect(0, 0, w, h);
    if (!room) return;
    var shook = NEU.juice ? NEU.juice.begin(ctx, w, h) : false;
    var ts = tilesets[room.tileset] || { colours: {} };
    var v = view();

    var cx0 = Math.max(0, Math.floor(camX / TILE));
    var cy0 = Math.max(0, Math.floor(camY / TILE));
    var cx1 = Math.min(room.w - 1, Math.ceil((camX + v.w) / TILE));
    var cy1 = Math.min(room.h - 1, Math.ceil((camY + v.h) / TILE));
    var atlas = ts.src ? images[ts.src] : null;
    var usable = atlas && atlas.complete && atlas.naturalWidth && !atlas.__failed;

    for (var cy = cy0; cy <= cy1; cy++) {
      for (var cx = cx0; cx <= cx1; cx++) {
        var ch = at(cx, cy);
        var sx = ((cx * TILE - camX) * SCALE) | 0;
        var sy = ((cy * TILE - camY) * SCALE) | 0;
        var s = TILE * SCALE;
        if (usable && ts.rects && ts.rects[ch]) {
          var r = ts.rects[ch];
          ctx.drawImage(atlas, r[0], r[1], TILE, TILE, sx, sy, s, s);
        } else {
          /* palette fallback — see note 2 */
          var col = (ts.colours && ts.colours[ch]) ||
                    (ch === 'i' ? '#2E3D52' : ch === 'M' ? '#4A4560' : ch === 'P' ? '#221D33' :
                     ts.solid.indexOf(ch) >= 0 ? '#1a1a24' : '#0d0d12');
          ctx.fillStyle = col;
          ctx.fillRect(sx, sy, s, s);
        }
      }
    }

    /* entities, then the player, sorted by foot Y so things in front
       overlap things behind */
    /* Plates first and unsorted — they are floor paint, and sorting
       them by foot Y makes a block vanish underneath its own plate. */
    for (var pi = 0; pi < ents.length; pi++)
      if (!ents[pi].dead && ents[pi].t === 'plate') drawEnt(ents[pi], now);

    /* An exit is normally a hole in the wall with nothing to draw — but
       one carrying a `sheet` is a THING, and blanket-filtering exits
       meant the only entity sheet binding in the whole game never drew.
       b7_altar's fire door has had `sheet: 'firedoor'` on it since the
       room was written and has never once appeared on screen. */
    var drawn = ents.filter(function (e) {
      return !e.dead && e.t !== 'trigger' && e.t !== 'plate' &&
             (e.t !== 'exit' || e.sheet); })
                    .map(function (e) { return { e: e, y: (e.y + 1) * TILE }; });
    drawn.push({ e: null, y: py });
    drawn.sort(function (a, b) { return a.y - b.y; });

    for (var i = 0; i < drawn.length; i++) {
      var d = drawn[i];
      if (!d.e) {
        var f = moving ? (1 + (((walked / 10) | 0) % 2)) : 0;
        /* SCALE, not 2. The world draws a pixel at 3 CSS px and the
           character drew one at 2, so the two never shared a grid and
           fine detail always fought the character. It also fixes a
           mismatch the other way: at 2 the sprite was 6 world units
           wide against a 10-unit collision box, so she read as smaller
           than the space she actually occupied. */
        stamp(BODIES[face].concat(LEGS[f]),
              ((px - camX) * SCALE) | 0, ((py - camY) * SCALE) | 0, SCALE);
        continue;
      }
      drawEnt(d.e, now);
    }

    /* the interact prompt */
    var n = nearest(promptable);
    if (n && !busy) {
      var p = entAt(n);
      ctx.fillStyle = '#EDE7DE';
      ctx.font = '16px "Determination Mono","Pixelify Sans",monospace';
      ctx.textAlign = 'center';
      ctx.fillText('e', ((p.x - camX) * SCALE) | 0, ((p.y - camY) * SCALE - 34 * SCALE / 3) | 0);
      ctx.textAlign = 'left';
    }

    /* A room can be dark. Same STEPPED falloff as the blackout — five
       discrete rings, not a soft vignette, because every other pixel
       on this site has a hard edge and a smooth gradient reads as a
       different program. `dark` may be a number or a hook (b6's goes
       out when its torch is placed); a `light` hook (a carried torch)
       centres the light on the returned point instead of the room. */
    var darkAmt = typeof room.dark === 'function' ? room.dark(API) : room.dark;
    if (darkAmt > 0) {
      var lt = room.light ? room.light(API) : null;
      var lx = lt ? ((lt.x - camX) * SCALE) : w / 2;
      var ly = lt ? ((lt.y - camY) * SCALE) : h / 2;
      var g = ctx.createRadialGradient(lx, ly, 0, lx, ly, darkAmt * SCALE / 2);
      g.addColorStop(0.00, 'rgba(0,0,0,0)');
      g.addColorStop(0.45, 'rgba(0,0,0,0)');
      g.addColorStop(0.46, 'rgba(0,0,0,0.55)');
      g.addColorStop(0.70, 'rgba(0,0,0,0.55)');
      g.addColorStop(0.71, 'rgba(0,0,0,0.86)');
      g.addColorStop(1.00, 'rgba(0,0,0,0.98)');
      ctx.fillStyle = g; ctx.fillRect(0, 0, w, h);
    }

    if (NEU.juice) { NEU.juice.drawParts(ctx, 1 / 60);
                     NEU.juice.end(ctx, shook);
                     NEU.juice.overlay(ctx, w, h); }

    if (fade > 0) {
      ctx.fillStyle = 'rgba(8,8,11,' + fade.toFixed(3) + ')';
      ctx.fillRect(0, 0, w, h);
    }
  }

  function drawEnt(e, now) {
    var p = entAt(e);
    var sx = ((p.x - camX) * SCALE) | 0, sy = ((p.y - camY) * SCALE) | 0;
    if (e.t === 'sign') {
      /* a post, a board, two carved lines — the castle's hints */
      ctx.fillStyle = '#6B4F2F';
      ctx.fillRect(sx - 11, sy - 26, 22, 18);
      ctx.fillStyle = '#3E2F1D';
      ctx.fillRect(sx - 2, sy - 8, 4, 8);
      ctx.fillStyle = '#C8B48A';
      ctx.fillRect(sx - 7, sy - 22, 14, 2);
      ctx.fillRect(sx - 5, sy - 17, 10, 2);
      return;
    }
    var sheet = e.sheet && NEU.sheets && NEU.sheets[e.sheet];
    if (sheet) {
      /* One blitter, in data/sheets.js — it is the only thing that
         knows about `cols`, and it is shared with both bosses. */
      if (NEU.sheetDraw && NEU.sheetDraw(ctx, e.sheet, sx, sy, {
            frame: sheet.fps ? null : (e.frame || 0),
            col: e.col || 0, scale: e.scale || 1,
            anchor: 'feet', now: now })) return;
      /* Missing art is LOUD. A silently absent sprite gets mistaken
         for a logic bug and costs an hour; a magenta box does not. */
      ctx.fillStyle = '#FF00A0';
      ctx.fillRect(sx - 12, sy - 24, 24, 24);
      return;
    }
    if (e.t === 'plate') {
      /* Drawn UNDER everything and inset, so a block sitting on one is
         still visibly a block on a plate rather than a block. A slide-
         armed plate stays lit once it locks. */
      var lit = !!entHere(e.x, e.y, 'block') || !!e.armed;
      ctx.fillStyle = lit ? '#7BE38A' : '#4A4560';
      ctx.fillRect(sx - 6 * SCALE / 2, sy - 6 * SCALE / 2 - 2, 6 * SCALE, 6 * SCALE / 2);
      return;
    }
    if (e.t === 'block') {
      var s2 = 14 * SCALE / 2;
      ctx.fillStyle = '#3A3245'; ctx.fillRect(sx - s2, sy - s2 * 2, s2 * 2, s2 * 2);
      ctx.fillStyle = '#564B66'; ctx.fillRect(sx - s2 + 2, sy - s2 * 2 + 2, s2 * 2 - 4, s2 * 2 - 4);
      ctx.fillStyle = '#241d2e'; ctx.fillRect(sx - s2, sy - 3, s2 * 2, 3);
      return;
    }
    if (e.t === 'brazier') {
      var on = !!e.lit;
      ctx.fillStyle = '#241d2e';
      ctx.fillRect(sx - 5 * SCALE / 2, sy - 12, 5 * SCALE, 12);
      ctx.fillStyle = on ? '#E4C46A' : '#2A2A38';
      var wob = on ? ((now / 90 | 0) % 2) * 2 : 0;
      ctx.fillRect(sx - 4 * SCALE / 2, sy - 22 - wob, 4 * SCALE, 12 + wob);
      if (on) { ctx.fillStyle = '#FFF2C4'; ctx.fillRect(sx - 3, sy - 18 - wob, 6, 6); }
      return;
    }
    if (PROP[e.t]) {
      /* 2 is the player's pixel size, so a prop and a person are on the
         same grid. The save point breathes; the altar does not. */
      var pr = PROP[e.t];
      if (e.t === 'save') {
        var pulse = 1 + Math.sin(now / 420) * 0.06;
        ctx.save();
        ctx.globalAlpha = 0.85 + Math.sin(now / 420) * 0.15;
        stampPal(pr.rows, pr.pal, sx, (sy - 6 + (1 - pulse) * 8) | 0, SCALE);
        ctx.restore();
        return;
      }
      stampPal(pr.rows, pr.pal, sx, sy, SCALE);
      return;
    }
    ctx.fillStyle = e.colour || '#B892FF';
    ctx.fillRect(sx - 9, sy - 18, 18, 18);
  }

  /* ── input ────────────────────────────────────────────────────── */
  function keyName(e) {
    var k = e.key;
    if (k === 'ArrowLeft'  || k === 'a' || k === 'A') return 'left';
    if (k === 'ArrowRight' || k === 'd' || k === 'D') return 'right';
    if (k === 'ArrowUp'    || k === 'w' || k === 'W') return 'up';
    if (k === 'ArrowDown'  || k === 's' || k === 'S') return 'down';
    return null;
  }
  addEventListener('keydown', function (e) {
    if (!running) return;
    /* A minigame owns the page while it is open — the fight canvas
       sits over the room, but the room's keydown still listened to
       the same window and walked the character underneath it, and
       Escape left the room while the fight's own overlay was up. */
    if (NEU.activeMinigame) return;
    if (e.key === 'Escape') { e.preventDefault(); leave(); return; }
    if (e.key === 'e' || e.key === 'E') {
      e.preventDefault();
      if (busy) return;
      /* Interact first, push second. A block you are standing next to
         is almost never what you meant when there is an npc in reach. */
      var n = nearest(interactive);
      if (n) fire(n); else tryPush();
      return;
    }
    if (e.key === 'r' || e.key === 'R') { e.preventDefault(); if (!busy) resetPuzzle(); return; }
    var n = keyName(e); if (n) { keys[n] = true; e.preventDefault(); }
  });
  addEventListener('keyup', function (e) {
    if (!running || NEU.activeMinigame) return;
    var n = keyName(e); if (n) keys[n] = false;
  });
  /* Alt-tab away with a key held and the keyup never arrives — the
     player would keep walking the moment the tab comes back. Same
     release-all the touch layer does. */
  addEventListener('blur', function () { keys = {}; });
  document.addEventListener('visibilitychange', function () {
    if (document.hidden) keys = {};
  });

  /* ── talking ──────────────────────────────────────────────────── */
  function say(lines, who) { if (NEU.talk) NEU.talk(lines, who); }
  function flag(k, v) { return NEU.save ? NEU.save.flag(k, v) : null; }

  /* ── open / close ─────────────────────────────────────────────── */
  function enter(id, spawn) {
    if (!rooms[id]) return false;
    wrap.hidden = false;
    document.body.classList.add('is-playing');
    if (NEU.quest) NEU.quest.lock(true);
    layout();
    land(id, spawn);
    fade = 1; fadeDir = -1; fadeThen = null;
    keys = {}; busy = false;
    /* rhythm and craft re-enter while the room still runs — spawning a
       second loop here would tick everything at double speed. */
    if (!running) {
      running = true; last = performance.now();
      requestAnimationFrame(step);
    }
    return true;
  }

  /* ESC confirmation dialog utility */
  function confirmExit(minigameName, onConfirm) {
    if (document.getElementById('confirmExit')) return;
    var overlay = document.createElement('div');
    overlay.id = 'confirmExit';
    overlay.style.cssText = 'position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.85);z-index:95;display:flex;align-items:center;justify-content:center;';
    overlay.innerHTML = '<div style="background:#1A1016;padding:32px 48px;border:2px solid #E23B55;border-radius:4px;text-align:center;">' +
      '<p style="font:24px \"Determination Mono\",monospace;color:#EDE7DE;margin:0 0 16px;">Leave ' + minigameName + '?</p>' +
      '<p style="font:16px \"Undertale Sans\",cursive;color:#8A8598;margin:0 0 24px;">Enter = Yes &nbsp;·&nbsp; Escape = No</p>' +
      '<div style="font:14px monospace;color:#555;">Progress will be lost.</div></div>';
    document.body.appendChild(overlay);
    function cleanup() {
      document.body.removeChild(overlay);
      document.removeEventListener('keydown', onKey);
    }
    function onKey(e) {
      /* The overlay listens on document and the minigames on window —
         without stopping the bubble, Escape to decline would clean the
         overlay up, the window handler would see the keypress and
         immediately build a new one. The decline became a re-ask. */
      e.stopPropagation();
      if (e.key === 'Enter') { cleanup(); onConfirm(); }
      else if (e.key === 'Escape') { cleanup(); }
    }
    document.addEventListener('keydown', onKey);
  }

  /* The room's quit button is the same exit as its ESC: rooms cost
     nothing to leave, so it goes straight out — the save point is
     never far. It sat unwired, doing nothing, since the button was
     added to the markup. */
  var engQuitBtn = document.getElementById('engQuit');
  if (engQuitBtn) engQuitBtn.addEventListener('click', function () {
    if (!running) return;
    leave();
  });

  function leave() {
    running = false;
    wrap.hidden = true;
    document.body.classList.remove('is-playing');
    if (NEU.quest) NEU.quest.lock(false);
    if (NEU.hush) NEU.hush();
    if (NEU.save) { NEU.save.capture(); NEU.save.flush(); }
  }

  var API = {
    say: say, flag: flag,
    flagged: function (k) { return NEU.save ? NEU.save.flagged(k) : false; },
    give: function (i) { NEU.save && NEU.save.give(i); },
    has: function (i) { return NEU.save ? NEU.save.has(i) : false; },
    go: go, leave: leave,
    busy: function (on) { busy = !!on; },
    entHere: entHere, reset: resetPuzzle, check: checkPuzzle,
    ents: function () { return ents; },
    solved: function (id) { return NEU.save ? NEU.save.flagged('solved:' + id) : false; },
    markSolved: function (id) { NEU.save && NEU.save.flag('solved:' + id, 1); },
    /* the live room definition — rooms with hooks (dark, light, onReset)
       expose their state through it, and tests read it the same way */
    get room() { return room; },
    get player() { return { x: px, y: py, face: face }; }
  };

  NEU.engine = {
    register: register, tileset: tileset, enter: enter, leave: leave, go: go,
    confirmExit: confirmExit,
    where: function () { return room ? { room: room.id, spawn: room.__spawn } : null; },
    get running() { return running; },
    get room() { return room ? room.id : null; },
    /* Which zone the player is standing in, by tileset name. music.js
       keys its tracks off this rather than off a room-id prefix map:
       a second mapping would be a second source of truth and would
       drift the first time a room changed tileset. */
    zone: function () { return room ? room.tileset : null; },
    get rooms() { return Object.keys(rooms); },
    /* Read-only view of the tileset registry. The dev console uses it to
       answer "is this zone drawing art or falling back to colours", and
       fixes14 uses it to assert every zone carries src + rects at
       runtime rather than merely in the source text. */
    tilesets: function () { return tilesets; },
    api: API,
    /* dev */
    warp: function (id, spawn) { if (running) { land(id, spawn); } else { enter(id, spawn); } },
    drawPlayer: drawPlayer,
    TILE: TILE, SCALE: SCALE
  };
})();
