/* engine.js — rooms, as data.
   ───────────────────────────────────────────────────────────────────
   Act IV is ~35 rooms. The existing scenes each hand-code their own
   movement, their own collision and their own interaction, which was
   right for three of them and is how a codebase dies at thirty-five:
   thirty-five slightly different collision bugs, none of them the same
   shape twice.

   So: one implementation, and rooms become DATA.

   The five decisions this file rests on:

   1. TILES ARE A STRING, one character per cell. A room is about a
      kilobyte of text you can read and edit in place. Binary or JSON
      arrays would be smaller and completely unreadable, and the thing
      that actually costs time here is authoring, not bytes.

   2. TILESETS HAVE A PALETTE FALLBACK. A tileset can point at an
      atlas image OR at a table of flat colours. That means every room
      is playable and testable the moment its layout exists, before
      any art for it does — no phase is ever blocked waiting on a
      sprite sheet.

   3. COLLISION IS SWEPT, ALWAYS. The player moves fast enough to
      cross a 16px tile in a frame at 60fps and much further on a
      120Hz display. Point-testing the destination tunnels through
      walls; the same bug already cost this project a round when the
      thrown key passed through the cube door. Movement is resolved
      axis-by-axis against the tiles the whole segment crosses.

   4. THE WALK CYCLE ADVANCES ON DISTANCE, NOT TIME. Lifted verbatim
      out of dark.js, which is where it was proven. Time-driven legs
      keep walking when you stop and slide when you change speed.

   5. THE CAMERA HAS A DEAD ZONE AND CLAMPS TO THE ROOM. Without a
      dead zone the whole world jitters under a player who is nudging
      one pixel at a time; without clamping you see past the edge of
      the map, which instantly reads as broken.

   Everything renders with integer fillRect / drawImage at DPR with
   smoothing off — same rules as the rest of the site.               */

(function () {
  'use strict';

  var NEU = window.NEU = window.NEU || {};

  var wrap = document.getElementById('eng');
  var cv   = document.getElementById('engCanvas');
  if (!wrap || !cv) { NEU.engine = { enter: function () {}, leave: function () {} }; return; }
  var ctx = cv.getContext ? cv.getContext('2d') : null;
  if (!ctx) { NEU.engine = { enter: function () {}, leave: function () {} }; return; }

  var reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;

  var TILE = 16;              // world units per cell
  var SCALE = 3;              // drawn at 3x — 48px cells, readable, pixel-exact
  var SPEED = 96;             // world units/sec
  var PLAYER_W = 10, PLAYER_H = 8;   // the FEET box. smaller than the sprite.
  var REACH = 22;

  /* ── state ────────────────────────────────────────────────────── */
  var rooms = {}, tilesets = {};
  var room = null, running = false, last = 0;
  var px = 0, py = 0, keys = {}, face = 'down', walked = 0, moving = false;
  var camX = 0, camY = 0;
  var fade = 0, fadeDir = 0, fadeThen = null;
  var busy = false;                    // a cutscene owns input
  var ents = [];                       // live copy of room.entities
  var images = {};

  /* ── the character ────────────────────────────────────────────────
     Same 9x13 cells as dark.js. Right is generated by mirroring left,
     so only three directions are drawn by hand. */
  var PAL = { h: '#241d2e', s: '#E8DCC8', e: '#241d2e', c: '#6F5FA6', b: '#191426' };
  function mirror(rows) {
    return rows.map(function (r) { return r.split('').reverse().join(''); });
  }
  var BODY_DOWN = ['..hhhhh..','.hhhhhhh.','.hsssssh.','.hsesesh.','.hsssssh.',
                   '..sssss..','.ccccccc.','scccccccs','.ccccccc.','..ccccc..'];
  var BODY_UP   = ['..hhhhh..','.hhhhhhh.','.hhhhhhh.','.hhhhhhh.','.hhhhhhh.',
                   '..sssss..','.ccccccc.','scccccccs','.ccccccc.','..ccccc..'];
  var BODY_LEFT = ['..hhhh...','.hhhhhh..','.hssssh..','.essssh..','.hssssh..',
                   '..sssss..','..ccccc..','.sccccc..','..ccccc..','..cccc...'];
  var LEGS = [['..c...c..','..b...b..','..b...b..'],
              ['...c.c...','...b.b...','..b...b..'],
              ['..c...c..','..bb.bb..','..b...b..']];
  var BODIES = { down: BODY_DOWN, up: BODY_UP, left: BODY_LEFT, right: mirror(BODY_LEFT) };

  function stamp(rows, cx, cy, s) {
    var h = rows.length, w = rows[0].length;
    var x0 = (cx - w * s / 2) | 0, y0 = (cy - h * s) | 0;   // anchored at the feet
    for (var r = 0; r < h; r++) for (var c = 0; c < w; c++) {
      var ch = rows[r][c];
      if (ch === '.' || !PAL[ch]) continue;
      ctx.fillStyle = PAL[ch];
      ctx.fillRect(x0 + c * s, y0 + r * s, s, s);
    }
  }

  function drawPlayer(targetCtx, sx, sy, fce, wlk, mov, anchorFeet, sc) {
    var c = targetCtx || ctx;
    var s = sc || 2;
    var f = mov ? (1 + (((wlk / (anchorFeet ? 10 : 16)) | 0) % 2)) : 0;
    var rows = BODIES[fce || 'down'].concat(LEGS[f]);
    var h = rows.length, w = rows[0].length;
    var x0 = (sx - w * s / 2) | 0;
    var y0 = anchorFeet ? ((sy - h * s) | 0) : ((sy - h * s / 2) | 0);
    for (var r = 0; r < h; r++) for (var cl = 0; cl < w; cl++) {
      var ch = rows[r][cl];
      if (ch === '.' || !PAL[ch]) continue;
      c.fillStyle = PAL[ch];
      c.fillRect(x0 + cl * s, y0 + r * s, s, s);
    }
  }

  /* ── tilesets ─────────────────────────────────────────────────── */
  function tileset(name, def) {
    /* def = { solid:'#XT', colours:{ '#':'#1a1a24', '.':'#0d0d12' },
               src:'img/...png', rects:{ '#':[0,0], '.':[16,0] } }     */
    tilesets[name] = def;
    if (def.src) img(def.src);
    return def;
  }

  function img(src) {
    if (images[src]) return images[src];
    var i = new Image();
    i.onerror = function () { i.__failed = true; };
    i.src = src;
    images[src] = i;
    return i;
  }

  /* ── rooms ────────────────────────────────────────────────────── */
  function register(id, def) {
    def.id = id;
    def.grid = def.tiles.split('\n').filter(function (r) { return r.length; });
    def.h = def.grid.length;
    def.w = def.grid.reduce(function (m, r) { return Math.max(m, r.length); }, 0);
    rooms[id] = def;
    return def;
  }

  function at(cx, cy) {
    if (!room) return '#';
    if (cx < 0 || cy < 0 || cy >= room.h) return '#';
    var r = room.grid[cy];
    if (cx >= r.length) return '#';
    return r[cx];
  }

  function solidAt(cx, cy) {
    var ts = tilesets[room.tileset];
    var ch = at(cx, cy);
    return !ts || ts.solid.indexOf(ch) >= 0;
  }

  /* Box-vs-tiles. Tests every cell the box overlaps rather than its
     corners — a box wider than a tile can straddle a wall with all
     four corners in open space. */
  function blocked(x, y) {
    var x0 = Math.floor((x - PLAYER_W / 2) / TILE);
    var x1 = Math.floor((x + PLAYER_W / 2 - 0.01) / TILE);
    var y0 = Math.floor((y - PLAYER_H) / TILE);
    var y1 = Math.floor((y - 0.01) / TILE);
    for (var cy = y0; cy <= y1; cy++)
      for (var cx = x0; cx <= x1; cx++) {
        if (solidAt(cx, cy)) return true;
        if (entSolid(cx, cy)) return true;
      }
    return false;
  }

  /* Entities can occupy the grid too — a push block is not a tile,
     because tiles are immutable strings and a block that moves has to
     be a thing with a position. */
  function entSolid(cx, cy) {
    for (var i = 0; i < ents.length; i++) {
      var e = ents[i];
      if (e.dead || !e.solid) continue;
      if (e.x === cx && e.y === cy) return true;
    }
    return false;
  }

  function entHere(cx, cy, kind) {
    for (var i = 0; i < ents.length; i++) {
      var e = ents[i];
      if (e.dead) continue;
      if (e.x === cx && e.y === cy && (!kind || e.t === kind)) return e;
    }
    return null;
  }

  /* ── push blocks ────────────────────────────────────────────────
     Walk into one and it moves a whole cell in the direction you are
     facing, if the cell beyond is clear. Grid-snapped rather than
     free — a block that slides continuously can end up straddling two
     cells, and then "is it on the plate" has no honest answer.

     There is no undo. Instead, an unsolvable arrangement resets the
     WHOLE room (`resetPuzzle`), which is Deltarune's answer and the
     right one: undo makes you think about the interface, a reset makes
     you think about the puzzle. */
  var DIRV = { up: [0, -1], down: [0, 1], left: [-1, 0], right: [1, 0] };

  function tryPush() {
    var d = DIRV[face];
    if (!d) return false;
    /* the cell directly in front of the player's feet */
    var cx = Math.floor(px / TILE) + d[0];
    var cy = Math.floor((py - 1) / TILE) + d[1];
    var b = entHere(cx, cy, 'block');
    if (!b || !b.push) return false;
    var tx = cx + d[0], ty = cy + d[1];
    if (solidAt(tx, ty) || entSolid(tx, ty)) return false;
    b.x = tx; b.y = ty;
    if (NEU.juice) NEU.juice.hit('tick');
    /* Ice. The block keeps going until something stops it, which is
       what turns "push a block" into "aim a block". Bounded by the
       room size so a malformed map cannot spin forever. */
    var guard = 0;
    while (at(b.x, b.y) === 'i' && guard++ < 64) {
      var nx = b.x + d[0], ny = b.y + d[1];
      if (solidAt(nx, ny) || entSolid(nx, ny)) break;
      b.x = nx; b.y = ny;
    }
    if (NEU.sfx && NEU.sfx.snap) NEU.sfx.snap();
    checkPuzzle();
    return true;
  }

  /* A room is solved when every plate has a block on it. Rooms can
     override with their own `solved(ctx)` for the ones that are not
     about blocks. */
  function checkPuzzle() {
    if (!room || room.__solved) return;
    var done;
    if (typeof room.solved === 'function') done = room.solved(API);
    else {
      var plates = ents.filter(function (e) { return e.t === 'plate' && !e.dead; });
      done = plates.length > 0 && plates.every(function (p) {
        var b = entHere(p.x, p.y, 'block');
        return !!b;
      });
    }
    if (!done) return;
    room.__solved = true;
    if (NEU.sfx && NEU.sfx.tick) NEU.sfx.tick();
    /* Solving a room is a LARGE moment. It is the only reward the
       puzzle gives and it should feel like one. */
    if (NEU.juice) NEU.juice.hit('large', { colour: '#7BE38A' });
    if (room.onSolved) room.onSolved(API);
  }

  function resetPuzzle() {
    if (!room) return;
    room.__solved = false;
    ents = spawnEnts(room);
    say(['the room resets itself. it has done this before.'], 'narr');
  }

  /* Swept along one axis: step in whole sub-steps no larger than half
     a tile, stopping at the last legal position. This is what stops
     fast movement tunnelling, and it degrades gracefully on a slow
     frame instead of teleporting through a wall. */
  function sweep(x, y, dx, dy) {
    var dist = Math.hypot(dx, dy);
    if (!dist) return { x: x, y: y };
    var steps = Math.max(1, Math.ceil(dist / (TILE / 2)));
    var sx = dx / steps, sy = dy / steps;
    for (var i = 0; i < steps; i++) {
      if (!blocked(x + sx, y)) x += sx;
      if (!blocked(x, y + sy)) y += sy;
    }
    return { x: x, y: y };
  }

  /* ── entities ─────────────────────────────────────────────────── */
  function entAt(e) { return { x: (e.x + 0.5) * TILE, y: (e.y + 1) * TILE }; }

  /* What `fire` can actually DO something with — the list below is
     exactly the set of branches fire() has.

     This exists because the E handler was `if (nearest()) fire(it); else
     tryPush()`, and `nearest` returned whatever entity was closest
     including blocks and plates. fire() has no branch for either, so it
     returned in silence and tryPush() was never reached: standing
     correctly against a block with open floor beyond it and pressing e
     did nothing, in every room, for every block. Every block puzzle in
     the game was unsolvable no matter how the room was laid out. */
  function interactive(e) {
    return typeof e.run === 'function' ||
           e.t === 'exit' || e.t === 'pickup' || e.t === 'save' ||
           e.t === 'npc'  || e.t === 'altar';
  }

  /* A pushable block is worth an `e` prompt even though pressing e goes
     through tryPush rather than fire. A plate is not: it is floor paint
     and there has never been anything to press. */
  function promptable(e) { return interactive(e) || (e.t === 'block' && e.push); }

  function nearest(want) {
    var best = null, bd = REACH;
    for (var i = 0; i < ents.length; i++) {
      var e = ents[i];
      if (e.dead || e.t === 'trigger') continue;
      if (want && !want(e)) continue;
      var p = entAt(e);
      var d = Math.hypot(p.x - px, p.y - (py - PLAYER_H / 2));
      if (d < bd) { bd = d; best = e; }
    }
    return best;
  }

  function fire(e) {
    if (!e) return;
    if (e.t === 'exit') {
      /* A locked door says what it is waiting for. "Nothing happens"
         is the least useful sentence a game can produce. */
      if (e.locked && !(NEU.save && NEU.save.flagged(e.locked))) {
        say(e.lines || ['it will not move yet.'], 'narr');
        if (NEU.sfx && NEU.sfx.locked) NEU.sfx.locked();
        return;
      }
      go(e.to, e.spawn); return;
    }
    if (e.t === 'pickup') {
      if (e.dead) return;
      e.dead = true;
      NEU.save && NEU.save.give(e.item);
      say(e.lines || ['you take it.'], e.who || 'narr');
      NEU.sfx && NEU.sfx.snap && NEU.sfx.snap();
      /* SMALL. A pickup must register without competing with a boss
         death — the tier table is what keeps that honest. */
      if (NEU.juice) {
        var pp = entAt(e);
        NEU.juice.hit('small');
        NEU.juice.burst((pp.x - camX) * SCALE, (pp.y - camY) * SCALE, 10, '#B892FF');
      }
      return;
    }
    if (e.t === 'save') {
      NEU.save && NEU.save.capture();
      NEU.save && NEU.save.flush();
      say(['saved.'], 'narr');
      NEU.sfx && NEU.sfx.tick && NEU.sfx.tick();
      return;
    }
    if (e.t === 'npc') {
      /* A run hook wins over lines. Entities that are only a hook —
         the mushrooms, the witch, the merchant — answer differently
         depending on the state of the world, and a fixed `lines`
         array cannot do that. */
      if (typeof e.run === 'function') { e.run(API); return; }
      say(e.lines || ['...'], e.who || 'narr'); return;
    }
    if (e.t === 'altar') {
      if (!NEU.save || !NEU.save.has(e.needs)) {
        say(e.empty || ['it wants something you do not have.'], 'narr');
        return;
      }
      NEU.save.take(e.needs);
      flag(e.gives, 1);
      say(e.lines || ['it takes it.'], 'narr');
      return;
    }
    if (typeof e.run === 'function') e.run(API);
  }

  function checkTriggers() {
    for (var i = 0; i < ents.length; i++) {
      var e = ents[i];
      if (e.t !== 'trigger' || e.dead) continue;
      var x0 = e.x * TILE, y0 = e.y * TILE;
      var x1 = x0 + (e.w || 1) * TILE, y1 = y0 + (e.h || 1) * TILE;
      if (px >= x0 && px <= x1 && py >= y0 && py <= y1) {
        if (e.once) e.dead = true;
        if (typeof e.run === 'function') e.run(API);
      }
    }
  }

  /* ── transitions ──────────────────────────────────────────────── */
  function go(id, spawn) {
    if (!rooms[id]) { say(['there is nothing through there. yet.'], 'narr'); return; }
    if (fadeDir) return;                    // already moving
    busy = true;
    fadeDir = 1;
    fadeThen = function () {
      land(id, spawn);
      fadeDir = -1;
      fadeThen = function () { busy = false; };
    };
    if (reduced) { fade = 1; }              // no crossfade, just the cut
  }

  function spawnEnts(r) {
    return (r.entities || []).map(function (e) {
      var c = {}; for (var k in e) c[k] = e[k];
      /* Pickups already taken and one-shot triggers already fired stay
         gone across a reload — otherwise the save file quietly hands
         out infinite copies of every item. */
      if (c.t === 'pickup' && NEU.save && NEU.save.has(c.item)) c.dead = true;
      if (c.once && NEU.save && NEU.save.flagged('t:' + r.id + ':' + c.x + ',' + c.y)) c.dead = true;
      return c;
    });
  }

  /* Only reached by a room that declares no spawns at all: the first cell
     you could actually stand in, in reading order. */
  function firstOpenCell() {
    for (var y = 0; y < room.h; y++)
      for (var x = 0; x < room.w; x++)
        if (!solidAt(x, y)) return { x: x, y: y };
    return { x: 2, y: 2 };
  }

  function land(id, spawn) {
    if (room && room.onExit) room.onExit(API);
    room = rooms[id];
    /* A solved puzzle stays solved across a revisit, but the blocks go
       back to their starting cells — otherwise re-entering a solved
       room shows an arrangement that no longer means anything. */
    room.__solved = NEU.save ? NEU.save.flagged('solved:' + id) : false;
    ents = spawnEnts(room);
    var s = (room.spawns && room.spawns[spawn]) || (room.spawns && room.spawns.default);
    if (!s) {
      /* An exit naming a spawn the target room does not declare used to
         fall through to a hard-coded {x:2,y:2}. That cell is inside a
         wall in four of the rooms shipped here and the wrong end of the
         room in the rest, so a single typo in an exit became a silent
         soft-lock that no spawn check could see — d3_square was exactly
         this. Prefer any spawn the room really declares, then go looking
         for floor, and say so out loud: a missing spawn is a bug in the
         room and it should not be able to pass for level design. */
      var names = room.spawns ? Object.keys(room.spawns) : [];
      s = names.length ? room.spawns[names[0]] : firstOpenCell();
      if (window.console && console.warn)
        console.warn('[neu] room "' + id + '" has no spawn "' + spawn +
                     '" — landing at ' + s.x + ',' + s.y);
    }
    px = (s.x + 0.5) * TILE; py = (s.y + 1) * TILE;
    walked = 0; face = s.face || 'down';
    room.__spawn = spawn;
    camSnap();
    if (room.onEnter) room.onEnter(API);
    if (NEU.save) NEU.save.capture();
  }

  /* ── camera ───────────────────────────────────────────────────── */
  function view() {
    return { w: innerWidth / SCALE, h: innerHeight / SCALE };
  }
  function camClamp() {
    var v = view();
    var maxX = Math.max(0, room.w * TILE - v.w), maxY = Math.max(0, room.h * TILE - v.h);
    camX = Math.min(Math.max(camX, 0), maxX);
    camY = Math.min(Math.max(camY, 0), maxY);
    if (room.w * TILE < v.w) camX = (room.w * TILE - v.w) / 2;
    if (room.h * TILE < v.h) camY = (room.h * TILE - v.h) / 2;
  }
  function camSnap() {
    var v = view();
    camX = px - v.w / 2; camY = py - v.h / 2;
    camClamp();
  }
  function camFollow() {
    /* Dead zone: the camera only moves once the player leaves the
       middle third. Without it, one-pixel nudges shake the world. */
    var v = view();
    var dzx = v.w * 0.16, dzy = v.h * 0.16;
    var cx = camX + v.w / 2, cy = camY + v.h / 2;
    if (px - cx >  dzx) camX += (px - cx) - dzx;
    if (px - cx < -dzx) camX += (px - cx) + dzx;
    if (py - cy >  dzy) camY += (py - cy) - dzy;
    if (py - cy < -dzy) camY += (py - cy) + dzy;
    camClamp();
  }

  /* ── loop ─────────────────────────────────────────────────────── */
  function layout() {
    var dpr = Math.min(devicePixelRatio || 1, 2);
    cv.width = (innerWidth * dpr) | 0; cv.height = (innerHeight * dpr) | 0;
    cv.style.width = innerWidth + 'px'; cv.style.height = innerHeight + 'px';
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.imageSmoothingEnabled = false;
    if (room) camClamp();
  }
  addEventListener('resize', function () { if (running) layout(); });

  function step(now) {
    if (!running) return;
    requestAnimationFrame(step);
    var dt = Math.min(0.033, (now - last) / 1000); last = now;

    if (fadeDir) {
      fade += fadeDir * dt / 0.22;
      if (fade >= 1 && fadeDir > 0) { fade = 1; fadeDir = 0; var f = fadeThen; fadeThen = null; f && f(); }
      else if (fade <= 0 && fadeDir < 0) { fade = 0; fadeDir = 0; var g = fadeThen; fadeThen = null; g && g(); }
    }

    if (room && !busy) {
      var vx = (keys.right ? 1 : 0) - (keys.left ? 1 : 0);
      var vy = (keys.down ? 1 : 0) - (keys.up ? 1 : 0);
      moving = !!(vx || vy);
      if (vx && vy) { vx *= 0.7071; vy *= 0.7071; }
      if (moving) {
        face = Math.abs(vx) > Math.abs(vy) ? (vx > 0 ? 'right' : 'left')
                                           : (vy > 0 ? 'down' : 'up');
        var before = px, bY = py;
        var p = sweep(px, py, vx * SPEED * dt, vy * SPEED * dt);
        px = p.x; py = p.y;
        walked += Math.hypot(px - before, py - bY);
        checkTriggers();
      }
      camFollow();
    }
    draw(now);
  }

  function draw(now) {
    var w = innerWidth, h = innerHeight;
    ctx.fillStyle = '#08080B'; ctx.fillRect(0, 0, w, h);
    if (!room) return;
    var shook = NEU.juice ? NEU.juice.begin(ctx, w, h) : false;
    var ts = tilesets[room.tileset] || { colours: {} };
    var v = view();

    var cx0 = Math.max(0, Math.floor(camX / TILE));
    var cy0 = Math.max(0, Math.floor(camY / TILE));
    var cx1 = Math.min(room.w - 1, Math.ceil((camX + v.w) / TILE));
    var cy1 = Math.min(room.h - 1, Math.ceil((camY + v.h) / TILE));
    var atlas = ts.src ? images[ts.src] : null;
    var usable = atlas && atlas.complete && atlas.naturalWidth && !atlas.__failed;

    for (var cy = cy0; cy <= cy1; cy++) {
      for (var cx = cx0; cx <= cx1; cx++) {
        var ch = at(cx, cy);
        var sx = ((cx * TILE - camX) * SCALE) | 0;
        var sy = ((cy * TILE - camY) * SCALE) | 0;
        var s = TILE * SCALE;
        if (usable && ts.rects && ts.rects[ch]) {
          var r = ts.rects[ch];
          ctx.drawImage(atlas, r[0], r[1], TILE, TILE, sx, sy, s, s);
        } else {
          /* palette fallback — see note 2 */
          var col = (ts.colours && ts.colours[ch]) ||
                    (ch === 'i' ? '#2E3D52' : ch === 'M' ? '#4A4560' : ch === 'P' ? '#221D33' :
                     ts.solid.indexOf(ch) >= 0 ? '#1a1a24' : '#0d0d12');
          ctx.fillStyle = col;
          ctx.fillRect(sx, sy, s, s);
        }
      }
    }

    /* entities, then the player, sorted by foot Y so things in front
       overlap things behind */
    /* Plates first and unsorted — they are floor paint, and sorting
       them by foot Y makes a block vanish underneath its own plate. */
    for (var pi = 0; pi < ents.length; pi++)
      if (!ents[pi].dead && ents[pi].t === 'plate') drawEnt(ents[pi], now);

    var drawn = ents.filter(function (e) {
      return !e.dead && e.t !== 'trigger' && e.t !== 'exit' && e.t !== 'plate'; })
                    .map(function (e) { return { e: e, y: (e.y + 1) * TILE }; });
    drawn.push({ e: null, y: py });
    drawn.sort(function (a, b) { return a.y - b.y; });

    for (var i = 0; i < drawn.length; i++) {
      var d = drawn[i];
      if (!d.e) {
        var f = moving ? (1 + (((walked / 10) | 0) % 2)) : 0;
        stamp(BODIES[face].concat(LEGS[f]),
              ((px - camX) * SCALE) | 0, ((py - camY) * SCALE) | 0, 2 * SCALE / 3 | 0 || 2);
        continue;
      }
      drawEnt(d.e, now);
    }

    /* the interact prompt */
    var n = nearest(promptable);
    if (n && !busy) {
      var p = entAt(n);
      ctx.fillStyle = '#EDE7DE';
      ctx.font = '16px "Determination Mono","Pixelify Sans",monospace';
      ctx.textAlign = 'center';
      ctx.fillText('e', ((p.x - camX) * SCALE) | 0, ((p.y - camY) * SCALE - 34 * SCALE / 3) | 0);
      ctx.textAlign = 'left';
    }

    /* A room can be dark. Same STEPPED falloff as the blackout — five
       discrete rings, not a soft vignette, because every other pixel
       on this site has a hard edge and a smooth gradient reads as a
       different program. */
    if (room.dark) {
      var g = ctx.createRadialGradient(w / 2, h / 2, 0, w / 2, h / 2, room.dark * SCALE / 2);
      g.addColorStop(0.00, 'rgba(0,0,0,0)');
      g.addColorStop(0.45, 'rgba(0,0,0,0)');
      g.addColorStop(0.46, 'rgba(0,0,0,0.55)');
      g.addColorStop(0.70, 'rgba(0,0,0,0.55)');
      g.addColorStop(0.71, 'rgba(0,0,0,0.86)');
      g.addColorStop(1.00, 'rgba(0,0,0,0.98)');
      ctx.fillStyle = g; ctx.fillRect(0, 0, w, h);
    }

    if (NEU.juice) { NEU.juice.drawParts(ctx, 1 / 60);
                     NEU.juice.end(ctx, shook);
                     NEU.juice.overlay(ctx, w, h); }

    if (fade > 0) {
      ctx.fillStyle = 'rgba(8,8,11,' + fade.toFixed(3) + ')';
      ctx.fillRect(0, 0, w, h);
    }
  }

  function drawEnt(e, now) {
    var p = entAt(e);
    var sx = ((p.x - camX) * SCALE) | 0, sy = ((p.y - camY) * SCALE) | 0;
    var sheet = e.sheet && NEU.sheets && NEU.sheets[e.sheet];
    if (sheet) {
      var im = img(sheet.src);
      if (im.complete && im.naturalWidth && !im.__failed) {
        var fr = sheet.fps ? (((now / (1000 / sheet.fps)) | 0) % sheet.frames) : (e.frame || 0);
        var dw = sheet.fw * (e.scale || 1), dh = sheet.fh * (e.scale || 1);
        ctx.drawImage(im, 0, fr * sheet.fh, sheet.fw, sheet.fh,
                      (sx - dw / 2) | 0, (sy - dh) | 0, dw | 0, dh | 0);
        return;
      }
      /* Missing art is LOUD. A silently absent sprite gets mistaken
         for a logic bug and costs an hour; a magenta box does not. */
      ctx.fillStyle = '#FF00A0';
      ctx.fillRect(sx - 12, sy - 24, 24, 24);
      return;
    }
    if (e.t === 'plate') {
      /* Drawn UNDER everything and inset, so a block sitting on one is
         still visibly a block on a plate rather than a block. */
      var lit = !!entHere(e.x, e.y, 'block');
      ctx.fillStyle = lit ? '#7BE38A' : '#4A4560';
      ctx.fillRect(sx - 6 * SCALE / 2, sy - 6 * SCALE / 2 - 2, 6 * SCALE, 6 * SCALE / 2);
      return;
    }
    if (e.t === 'block') {
      var s2 = 14 * SCALE / 2;
      ctx.fillStyle = '#3A3245'; ctx.fillRect(sx - s2, sy - s2 * 2, s2 * 2, s2 * 2);
      ctx.fillStyle = '#564B66'; ctx.fillRect(sx - s2 + 2, sy - s2 * 2 + 2, s2 * 2 - 4, s2 * 2 - 4);
      ctx.fillStyle = '#241d2e'; ctx.fillRect(sx - s2, sy - 3, s2 * 2, 3);
      return;
    }
    if (e.t === 'brazier') {
      var on = !!e.lit;
      ctx.fillStyle = '#241d2e';
      ctx.fillRect(sx - 5 * SCALE / 2, sy - 12, 5 * SCALE, 12);
      ctx.fillStyle = on ? '#E4C46A' : '#2A2A38';
      var wob = on ? ((now / 90 | 0) % 2) * 2 : 0;
      ctx.fillRect(sx - 4 * SCALE / 2, sy - 22 - wob, 4 * SCALE, 12 + wob);
      if (on) { ctx.fillStyle = '#FFF2C4'; ctx.fillRect(sx - 3, sy - 18 - wob, 6, 6); }
      return;
    }
    ctx.fillStyle = e.colour || '#B892FF';
    ctx.fillRect(sx - 9, sy - 18, 18, 18);
  }

  /* ── input ────────────────────────────────────────────────────── */
  function keyName(e) {
    var k = e.key;
    if (k === 'ArrowLeft'  || k === 'a' || k === 'A') return 'left';
    if (k === 'ArrowRight' || k === 'd' || k === 'D') return 'right';
    if (k === 'ArrowUp'    || k === 'w' || k === 'W') return 'up';
    if (k === 'ArrowDown'  || k === 's' || k === 'S') return 'down';
    return null;
  }
  addEventListener('keydown', function (e) {
    if (!running) return;
    if (e.key === 'Escape') { e.preventDefault(); leave(); return; }
    if (e.key === 'e' || e.key === 'E') {
      e.preventDefault();
      if (busy) return;
      /* Interact first, push second. A block you are standing next to
         is almost never what you meant when there is an npc in reach. */
      var n = nearest(interactive);
      if (n) fire(n); else tryPush();
      return;
    }
    if (e.key === 'r' || e.key === 'R') { e.preventDefault(); if (!busy) resetPuzzle(); return; }
    var n = keyName(e); if (n) { keys[n] = true; e.preventDefault(); }
  });
  addEventListener('keyup', function (e) {
    if (!running) return;
    var n = keyName(e); if (n) keys[n] = false;
  });

  /* ── talking ──────────────────────────────────────────────────── */
  function say(lines, who) { if (NEU.talk) NEU.talk(lines, who); }
  function flag(k, v) { return NEU.save ? NEU.save.flag(k, v) : null; }

  /* ── open / close ─────────────────────────────────────────────── */
  function enter(id, spawn) {
    if (!rooms[id]) return false;
    wrap.hidden = false;
    document.body.classList.add('is-playing');
    if (NEU.quest) NEU.quest.lock(true);
    layout();
    land(id, spawn);
    fade = 1; fadeDir = -1; fadeThen = null;
    keys = {}; busy = false;
    running = true; last = performance.now();
    requestAnimationFrame(step);
    return true;
  }

  function leave() {
    running = false;
    wrap.hidden = true;
    document.body.classList.remove('is-playing');
    if (NEU.quest) NEU.quest.lock(false);
    if (NEU.hush) NEU.hush();
    if (NEU.save) { NEU.save.capture(); NEU.save.flush(); }
  }

  var API = {
    say: say, flag: flag,
    flagged: function (k) { return NEU.save ? NEU.save.flagged(k) : false; },
    give: function (i) { NEU.save && NEU.save.give(i); },
    has: function (i) { return NEU.save ? NEU.save.has(i) : false; },
    go: go, leave: leave,
    busy: function (on) { busy = !!on; },
    entHere: entHere, reset: resetPuzzle, check: checkPuzzle,
    ents: function () { return ents; },
    solved: function (id) { return NEU.save ? NEU.save.flagged('solved:' + id) : false; },
    markSolved: function (id) { NEU.save && NEU.save.flag('solved:' + id, 1); },
    get player() { return { x: px, y: py, face: face }; }
  };

  NEU.engine = {
    register: register, tileset: tileset, enter: enter, leave: leave, go: go,
    where: function () { return room ? { room: room.id, spawn: room.__spawn } : null; },
    get running() { return running; },
    get room() { return room ? room.id : null; },
    /* Which zone the player is standing in, by tileset name. music.js
       keys its tracks off this rather than off a room-id prefix map:
       a second mapping would be a second source of truth and would
       drift the first time a room changed tileset. */
    zone: function () { return room ? room.tileset : null; },
    get rooms() { return Object.keys(rooms); },
    /* Read-only view of the tileset registry. The dev console uses it to
       answer "is this zone drawing art or falling back to colours", and
       fixes14 uses it to assert every zone carries src + rects at
       runtime rather than merely in the source text. */
    tilesets: function () { return tilesets; },
    api: API,
    /* dev */
    warp: function (id, spawn) { if (running) { land(id, spawn); } else { enter(id, spawn); } },
    drawPlayer: drawPlayer,
    TILE: TILE, SCALE: SCALE
  };
})();
